/*
 * This is the template generated by rpcgen
 * completed with the rpc server implementation
 */

#include "log_rpc.h"

bool_t
logging_1_svc(log_data l, int *result,  struct svc_req *rqstp)
{
    bool_t retval;

    if (strcmp(l.op, "PUBLISH") == 0 || strcmp(l.op, "DELETE") == 0) {
        printf("%s  %s  %s  %s", l.username, l.op, l.fileName, l.date_time);
    } else {
        printf("%s  %s   %s", l.username, l.op, l.date_time);
    }

    *result = 0;

    retval = TRUE;

    return retval;
}

int
log_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
    xdr_free (xdr_result, result);

    /*
     * Insert additional freeing code here, if needed
     */

    return 1;
}
